spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      database: ${REDIS_DB_INDEX}

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        debug: false
        smtp:
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000
          chunking: false
          auth: true
          ssl:
            enable: ${MAIL_SSLENABLED}
          starttls:
            enable: ${MAIL_TLSENABLED}

logging:
  level:
    application: ${LOGGER_LEVEL_ROOT}
    org.springframework: INFO

app:
  config:
    prefix: ""
    zone: "+3"
    api-path: "https://lknpd.nalog.ru/api/v1"
    referer: "Referer"
    mail-from: ${MAIL_FROM}
    mail-admin: ${MAIL_ADMIN}
    api-login: ${API_LOGIN}
    api-password: ${API_PASSWORD}
    delay: ${FIXED_DELAY}
  job:
    fixed-delay: ${FIXED_DELAY}
    initial-delay: ${INITIAL_DELAY}