name: CD Test

on:
  workflow_run:
    workflows: ["Java CI"]
    types:
      - completed

jobs:
  start:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'test'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

  build_and_push_to_docker_hub:
    name: Build&Push Docker image to DockerHub
    runs-on: ubuntu-latest
    needs: start
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to DockerHub
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/receipt-processing-service:test

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build_and_push_to_docker_hub
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate .env from example.env
        run: |
          cp example.env .env

          # Mail
          sed -i "s|MAIL_HOST=.*|MAIL_HOST=${{ secrets.MAIL_HOST_TEST }}|" .env
          sed -i "s|MAIL_USERNAME=.*|MAIL_USERNAME=${{ secrets.MAIL_USERNAME_TEST }}|" .env
          sed -i "s|MAIL_PASSWORD=.*|MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD_TEST }}|" .env
          sed -i "s|MAIL_FROM=.*|MAIL_FROM=${{ secrets.MAIL_FROM_TEST }}|" .env
          sed -i "s|MAIL_ADMIN=.*|MAIL_ADMIN=${{ secrets.MAIL_ADMIN_TEST }}|" .env

          # ApiNalog
          sed -i "s|API_LOGIN=.*|API_LOGIN=${{ secrets.API_LOGIN_TEST }}|" .env
          sed -i "s|API_PASSWORD=.*|API_PASSWORD=${{ secrets.API_PASSWORD_TEST }}|" .env


      - name: Copy docker-compose.test.yml and .env via ssh
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: |
            infra/docker-compose.test.yml
            infra/init.sql
            .env
          target: receipt-processing-service-test

      - name: Executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd receipt-processing-service-test
            sudo docker compose -f docker-compose.test.yml pull
            sudo docker compose -f docker-compose.test.yml down
            sudo docker compose -f docker-compose.test.yml up -d

  send_message:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: Deployment receipt-processing-service to the TEST environment was successful!